PRODUCTS_READ = "products:read"
CART_READ = "cart:read"
CART_WRITE = "cart:write"
ORDERS_READ = "orders:read"
ORDERS_WRITE = "orders:write"

SUPPORTED_SCOPES = [PRODUCTS_READ, CART_READ, CART_WRITE, ORDERS_READ, ORDERS_WRITE]
