/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PageRouteImport } from './pages/page'
import { Route as AccountPageRouteImport } from './pages/account/page'
import { Route as AuthorizePageRouteImport } from './pages/authorize/page'
import { Route as CartPageRouteImport } from './pages/cart/page'
import { Route as LoginPageRouteImport } from './pages/login/page'
import { Route as OrdersPageRouteImport } from './pages/orders/page'

const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPageRoute = AccountPageRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizePageRoute = AuthorizePageRouteImport.update({
  id: '/authorize/',
  path: '/authorize/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartPageRoute = CartPageRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPageRoute = LoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersPageRoute = OrdersPageRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/account/': typeof AccountPageRoute
  '/authorize/': typeof AuthorizePageRoute
  '/cart/': typeof CartPageRoute
  '/login/': typeof LoginPageRoute
  '/orders/': typeof OrdersPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/account': typeof AccountPageRoute
  '/authorize': typeof AuthorizePageRoute
  '/cart': typeof CartPageRoute
  '/login': typeof LoginPageRoute
  '/orders': typeof OrdersPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/account/': typeof AccountPageRoute
  '/authorize/': typeof AuthorizePageRoute
  '/cart/': typeof CartPageRoute
  '/login/': typeof LoginPageRoute
  '/orders/': typeof OrdersPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/account/' | '/authorize/' | '/cart/' | '/login/' | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/authorize' | '/cart' | '/login' | '/orders'
  id:
    | '__root__'
    | '/'
    | '/account/'
    | '/authorize/'
    | '/cart/'
    | '/login/'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  AccountPageRoute: typeof AccountPageRoute
  AuthorizePageRoute: typeof AuthorizePageRoute
  CartPageRoute: typeof CartPageRoute
  LoginPageRoute: typeof LoginPageRoute
  OrdersPageRoute: typeof OrdersPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize/': {
      id: '/authorize/'
      path: '/authorize'
      fullPath: '/authorize/'
      preLoaderRoute: typeof AuthorizePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  AccountPageRoute: AccountPageRoute,
  AuthorizePageRoute: AuthorizePageRoute,
  CartPageRoute: CartPageRoute,
  LoginPageRoute: LoginPageRoute,
  OrdersPageRoute: OrdersPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
