/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as PageRouteImport } from './pages/page'
import { Route as AuthorizePageRouteImport } from './pages/authorize/page'
import { Route as CartPageRouteImport } from './pages/cart/page'
import { Route as LoginPageRouteImport } from './pages/login/page'

const PageRoute = PageRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizePageRoute = AuthorizePageRouteImport.update({
  id: '/authorize/',
  path: '/authorize/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartPageRoute = CartPageRouteImport.update({
  id: '/cart/',
  path: '/cart/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPageRoute = LoginPageRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PageRoute
  '/authorize/': typeof AuthorizePageRoute
  '/cart/': typeof CartPageRoute
  '/login/': typeof LoginPageRoute
}
export interface FileRoutesByTo {
  '/': typeof PageRoute
  '/authorize': typeof AuthorizePageRoute
  '/cart': typeof CartPageRoute
  '/login': typeof LoginPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof PageRoute
  '/authorize/': typeof AuthorizePageRoute
  '/cart/': typeof CartPageRoute
  '/login/': typeof LoginPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/authorize/' | '/cart/' | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/authorize' | '/cart' | '/login'
  id: '__root__' | '/' | '/authorize/' | '/cart/' | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRoute
  AuthorizePageRoute: typeof AuthorizePageRoute
  CartPageRoute: typeof CartPageRoute
  LoginPageRoute: typeof LoginPageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize/': {
      id: '/authorize/'
      path: '/authorize'
      fullPath: '/authorize/'
      preLoaderRoute: typeof AuthorizePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart/': {
      id: '/cart/'
      path: '/cart'
      fullPath: '/cart/'
      preLoaderRoute: typeof CartPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRoute,
  AuthorizePageRoute: AuthorizePageRoute,
  CartPageRoute: CartPageRoute,
  LoginPageRoute: LoginPageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
